version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  accountdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: accountdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "NikolinAccount9!"
    ports:
      - "1433:1433"
    depends_on: 
      - rabbitmq
  ticketdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: ticketdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "NikolinPassword9!"
    ports:
      - "1434:1433"
    depends_on: 
      - rabbitmq
  paymentdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: paymentdb
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "NikolinPayment9!"
    ports:
      - "1435:1433"
  account:
    container_name: account
    build:
      dockerfile: Dockerfile
      context: ./AccountAPI
    ports:
      - 6001:80
    depends_on:
      - accountdb
  ticket:
    container_name: ticket
    build:
      dockerfile: Dockerfile
      context: ./TicketAPI
    ports:
      - 6002:80
    depends_on: 
      - ticketdb
  payment:
    container_name: payment
    build:
      dockerfile: Dockerfile
      context: ./PaymentAPI
    ports:
      - 6003:80
    depends_on: 
      - paymentdb