version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: accountsqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "NikolinPassword9!"
    ports:
      - "1433:1433"