apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/websocket-services: location-cluster-ip-service
spec:
  rules:
    - http:
        paths:
          - path: /account/?(.*)
            backend:
              serviceName: account-cluster-ip-service
              servicePort: 6001
          - path: /ticket/?(.*)
            backend:
              serviceName: ticket-cluster-ip-service
              servicePort: 6002
          - path: /payment/?(.*)
            backend:
              serviceName: payment-cluster-ip-service
              servicePort: 6003
          - path: /route/?(.*)
            backend:
              serviceName: route-cluster-ip-service
              servicePort: 6004
          - path: /
            backend:
              serviceName: location-cluster-ip-service
              servicePort: 3000
          