// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketAPI.Data;

namespace TicketAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201113013344_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketAPI.Models.Coefficient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Coefficients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserType = 1,
                            Value = 1.0
                        },
                        new
                        {
                            Id = 2,
                            UserType = 2,
                            Value = 0.80000000000000004
                        },
                        new
                        {
                            Id = 3,
                            UserType = 3,
                            Value = 0.84999999999999998
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TicketType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TicketType = 1
                        },
                        new
                        {
                            Id = 2,
                            TicketType = 2
                        },
                        new
                        {
                            Id = 3,
                            TicketType = 3
                        },
                        new
                        {
                            Id = 4,
                            TicketType = 4
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Pricelist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Pricelists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            From = new DateTime(2020, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            To = new DateTime(2020, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.PricelistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PricelistId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PricelistId");

                    b.ToTable("PricelistItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Price = 70.0,
                            PricelistId = 1
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            Price = 250.0,
                            PricelistId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 3,
                            Price = 1600.0,
                            PricelistId = 1
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 4,
                            Price = 12000.0,
                            PricelistId = 1
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("IssueTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PricelistItemId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Valid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PricelistItemId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IssueTime = new DateTime(2020, 8, 12, 8, 22, 12, 0, DateTimeKind.Unspecified),
                            Price = 70.0,
                            PricelistItemId = 1,
                            UserId = 3,
                            Valid = true
                        },
                        new
                        {
                            Id = 2,
                            IssueTime = new DateTime(2020, 6, 5, 16, 13, 56, 0, DateTimeKind.Unspecified),
                            Price = 250.0,
                            PricelistItemId = 2,
                            UserId = 3,
                            Valid = true
                        },
                        new
                        {
                            Id = 3,
                            IssueTime = new DateTime(2020, 11, 12, 10, 13, 0, 0, DateTimeKind.Unspecified),
                            Price = 10000.0,
                            PricelistItemId = 4,
                            UserId = 3,
                            Valid = true
                        });
                });

            modelBuilder.Entity("TicketAPI.Models.PricelistItem", b =>
                {
                    b.HasOne("TicketAPI.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketAPI.Models.Pricelist", "Pricelist")
                        .WithMany()
                        .HasForeignKey("PricelistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("TicketAPI.Models.PricelistItem", "PricelistItem")
                        .WithMany()
                        .HasForeignKey("PricelistItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
