apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountdb-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: accountdb
  template:
    metadata:
      labels:
        component: accountdb
    spec:
      containers:
        - name: accountdb
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: NikolinAccount9!
